// database/reports.js
// Auto-generated by: npx sutramcore-mysql import --reports
// Review: add labels, descriptions, and default param values
'use strict';

module.exports = [

  {
    report_name:    'monthly_report_bulk',
    label:          'Monthly Report Bulk',
    report_type:    'procedure',
    procedure_name: 'monthly_report_bulk',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'imonth', type: 'number', default: null },
    ],
  },

  {
    report_name:    'monthly_report_bulk_aj',
    label:          'Monthly Report Bulk Aj',
    report_type:    'procedure',
    procedure_name: 'monthly_report_bulk_aj',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'itype', type: 'string', default: null },
      { name: 'imonth', type: 'number', default: null },
    ],
  },

  {
    report_name:    'monthly_report_bulk_u',
    label:          'Monthly Report Bulk U',
    report_type:    'procedure',
    procedure_name: 'monthly_report_bulk_u',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'imonth', type: 'number', default: null },
    ],
  },

  {
    report_name:    'not_import_data',
    label:          'Not Import Data',
    report_type:    'procedure',
    procedure_name: 'not_import_data',
    params: [
      { name: 'dbname', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'imm_ID', type: 'number', default: null },
      { name: 'itype', type: 'number', default: null },
    ],
  },

  {
    report_name:    'report_yearly_bulk',
    label:          'Report Yearly Bulk',
    report_type:    'procedure',
    procedure_name: 'report_yearly_bulk',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'report_yearly_new',
    label:          'Report Yearly New',
    report_type:    'procedure',
    procedure_name: 'report_yearly_new',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'report_yearly_price',
    label:          'Report Yearly Price',
    report_type:    'procedure',
    procedure_name: 'report_yearly_price',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_aawakdetail_fordistribution',
    label:          'Sp Aawakdetail Fordistribution',
    report_type:    'procedure',
    procedure_name: 'sp_aawakdetail_fordistribution',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'itype_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aawakjawak_delete',
    label:          'Sp Aawakjawak Delete',
    report_type:    'procedure',
    procedure_name: 'sp_aawakjawak_delete',
    params: [
      { name: 'iid', type: 'number', default: null },
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aawaktype_delete',
    label:          'Sp Aawaktype Delete',
    report_type:    'procedure',
    procedure_name: 'sp_aawaktype_delete',
    params: [
      { name: 'iaawak_type_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_aawaktype_insert',
    label:          'Sp Aawaktype Insert',
    report_type:    'procedure',
    procedure_name: 'sp_aawaktype_insert',
    params: [
      { name: 'iaawak_type_hin', type: 'string', default: null },
      { name: 'iaawak_type_eng', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aawaktype_update',
    label:          'Sp Aawaktype Update',
    report_type:    'procedure',
    procedure_name: 'sp_aawaktype_update',
    params: [
      { name: 'iaawak_type_id', type: 'number', default: null },
      { name: 'iaawak_type_hin', type: 'string', default: null },
      { name: 'iaawak_type_eng', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aawak_insert',
    label:          'Sp Aawak Insert',
    report_type:    'procedure',
    procedure_name: 'sp_aawak_insert',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'isource_mm_id', type: 'number', default: null },
      { name: 'ientry_type', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'icompany_name', type: 'string', default: null },
      { name: 'iprice', type: 'string', default: null },
      { name: 'iaawak_source', type: 'number', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'iaawak_type', type: 'number', default: null },
      { name: 'iref_id', type: 'number', default: null },
      { name: 'iaawak_description', type: 'string', default: null },
      { name: 'iaawak_detail', type: 'string', default: null },
      { name: 'iquantity', type: 'number', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'ihighlight', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_aawak_rejected_delete',
    label:          'Sp Aawak Rejected Delete',
    report_type:    'procedure',
    procedure_name: 'sp_aawak_rejected_delete',
    params: [
      { name: 'iid', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_aawak_update',
    label:          'Sp Aawak Update',
    report_type:    'procedure',
    procedure_name: 'sp_aawak_update',
    params: [
      { name: 'iid', type: 'string', default: null },
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'icompany_name', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iquantity', type: 'number', default: null },
      { name: 'iprice', type: 'number', default: null },
      { name: 'iaawak_type', type: 'string', default: null },
      { name: 'iref_id', type: 'number', default: null },
      { name: 'iaawak_source', type: 'string', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'iaawak_description', type: 'string', default: null },
      { name: 'iaawak_detail', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'ibt_highlight', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aawak_voucher_select',
    label:          'Sp Aawak Voucher Select',
    report_type:    'procedure',
    procedure_name: 'sp_aawak_voucher_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_add_mm_entrysar',
    label:          'Sp Add Mm Entrysar',
    report_type:    'procedure',
    procedure_name: 'sp_add_mm_entrysar',
    params: [
      { name: 'iyear', type: 'number', default: null },
      { name: 'strMMIds', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_aj_mm_select_used',
    label:          'Sp Aj Mm Select Used',
    report_type:    'procedure',
    procedure_name: 'sp_aj_mm_select_used',
    params: [],
  },

  {
    report_name:    'sp_analyse_import_data',
    label:          'Sp Analyse Import Data',
    report_type:    'procedure',
    procedure_name: 'sp_analyse_import_data',
    params: [
      { name: 'dbname', type: 'string', default: null },
      { name: 'ist_date', type: 'string', default: null },
      { name: 'ien_date', type: 'string', default: null },
      { name: 'imm_ID', type: 'string', default: null },
      { name: 'flag', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_automatic_aawak',
    label:          'Sp Automatic Aawak',
    report_type:    'procedure',
    procedure_name: 'sp_automatic_aawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_automatic_jawak',
    label:          'Sp Automatic Jawak',
    report_type:    'procedure',
    procedure_name: 'sp_automatic_jawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istore_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_category_delete',
    label:          'Sp Category Delete',
    report_type:    'procedure',
    procedure_name: 'sp_category_delete',
    params: [
      { name: 'icategory_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_category_insert',
    label:          'Sp Category Insert',
    report_type:    'procedure',
    procedure_name: 'sp_category_insert',
    params: [
      { name: 'icategory_name', type: 'string', default: null },
      { name: 'icategory_name_eng', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_category_select',
    label:          'Sp Category Select',
    report_type:    'procedure',
    procedure_name: 'sp_category_select',
    params: [],
  },

  {
    report_name:    'sp_category_update',
    label:          'Sp Category Update',
    report_type:    'procedure',
    procedure_name: 'sp_category_update',
    params: [
      { name: 'icategory_id', type: 'number', default: null },
      { name: 'icategory_name', type: 'string', default: null },
      { name: 'icategory_name_eng', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_check_update',
    label:          'Sp Check Update',
    report_type:    'procedure',
    procedure_name: 'sp_check_update',
    params: [
      { name: 'iid', type: 'number', default: null },
      { name: 'ibt_check', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_check_voucher_update',
    label:          'Sp Check Voucher Update',
    report_type:    'procedure',
    procedure_name: 'sp_check_voucher_update',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'ibt_check_voucher', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_closingdate_check',
    label:          'Sp Closingdate Check',
    report_type:    'procedure',
    procedure_name: 'sp_closingdate_check',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closingdate_update',
    label:          'Sp Closingdate Update',
    report_type:    'procedure',
    procedure_name: 'sp_closingdate_update',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iupdate_date', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_allmm',
    label:          'Sp Closing Allmm',
    report_type:    'procedure',
    procedure_name: 'sp_closing_allmm',
    params: [
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'imm_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_delete',
    label:          'Sp Closing Delete',
    report_type:    'procedure',
    procedure_name: 'sp_closing_delete',
    params: [
      { name: 'iid', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_closing_delete_mix',
    label:          'Sp Closing Delete Mix',
    report_type:    'procedure',
    procedure_name: 'sp_closing_delete_mix',
    params: [
      { name: 'iid', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_report',
    label:          'Sp Closing Report',
    report_type:    'procedure',
    procedure_name: 'sp_closing_report',
    params: [
      { name: 'strmm_id', type: 'string', default: null },
      { name: 'dtStart', type: 'string', default: null },
      { name: 'dtEnd', type: 'string', default: null },
      { name: 'stritem_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_select',
    label:          'Sp Closing Select',
    report_type:    'procedure',
    procedure_name: 'sp_closing_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_select_mix',
    label:          'Sp Closing Select Mix',
    report_type:    'procedure',
    procedure_name: 'sp_closing_select_mix',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_update',
    label:          'Sp Closing Update',
    report_type:    'procedure',
    procedure_name: 'sp_closing_update',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iid', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iquantity', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_update_mix',
    label:          'Sp Closing Update Mix',
    report_type:    'procedure',
    procedure_name: 'sp_closing_update_mix',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iid', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iaawak_type', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iquantity', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_closing_update_mix_all',
    label:          'Sp Closing Update Mix All',
    report_type:    'procedure',
    procedure_name: 'sp_closing_update_mix_all',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iid_sewa', type: 'number', default: null },
      { name: 'iid_kharida', type: 'number', default: null },
      { name: 'iid_mix', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iqty_sewa', type: 'string', default: null },
      { name: 'iqty_kharida', type: 'string', default: null },
      { name: 'iqty_mix', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_copy_closing',
    label:          'Sp Copy Closing',
    report_type:    'procedure',
    procedure_name: 'sp_copy_closing',
    params: [
      { name: 'ids', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_description_delete',
    label:          'Sp Description Delete',
    report_type:    'procedure',
    procedure_name: 'sp_description_delete',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_description_insert',
    label:          'Sp Description Insert',
    report_type:    'procedure',
    procedure_name: 'sp_description_insert',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iaawak_type_id', type: 'number', default: null },
      { name: 'idescription_hin', type: 'string', default: null },
      { name: 'idescription_eng', type: 'string', default: null },
      { name: 'iaawak_date', type: 'string', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_description_select',
    label:          'Sp Description Select',
    report_type:    'procedure',
    procedure_name: 'sp_description_select',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iaawak_type_id', type: 'number', default: null },
      { name: 'iaawak_date', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_description_select_all',
    label:          'Sp Description Select All',
    report_type:    'procedure',
    procedure_name: 'sp_description_select_all',
    params: [],
  },

  {
    report_name:    'sp_description_update',
    label:          'Sp Description Update',
    report_type:    'procedure',
    procedure_name: 'sp_description_update',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iaawak_type_id', type: 'number', default: null },
      { name: 'idescription_hin', type: 'string', default: null },
      { name: 'idescription_eng', type: 'string', default: null },
      { name: 'iaawak_date', type: 'string', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_discription_name_select',
    label:          'Sp Discription Name Select',
    report_type:    'procedure',
    procedure_name: 'sp_discription_name_select',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_distribution_name_select',
    label:          'Sp Distribution Name Select',
    report_type:    'procedure',
    procedure_name: 'sp_distribution_name_select',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_edit_lastaawakentry',
    label:          'Sp Edit Lastaawakentry',
    report_type:    'procedure',
    procedure_name: 'sp_edit_lastaawakentry',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_edit_lastjawakentry',
    label:          'Sp Edit Lastjawakentry',
    report_type:    'procedure',
    procedure_name: 'sp_edit_lastjawakentry',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_getclosingstock_item',
    label:          'Sp Getclosingstock Item',
    report_type:    'procedure',
    procedure_name: 'sp_getclosingstock_item',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_get_aawakdetails',
    label:          'Sp Get Aawakdetails',
    report_type:    'procedure',
    procedure_name: 'sp_get_aawakdetails',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'ijawak_type_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_get_difference',
    label:          'Sp Get Difference',
    report_type:    'procedure',
    procedure_name: 'sp_get_difference',
    params: [
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_get_mmname',
    label:          'Sp Get Mmname',
    report_type:    'procedure',
    procedure_name: 'sp_get_mmname',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_get_notverifiedaawak',
    label:          'Sp Get Notverifiedaawak',
    report_type:    'procedure',
    procedure_name: 'sp_get_notverifiedaawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_get_openingdate',
    label:          'Sp Get Openingdate',
    report_type:    'procedure',
    procedure_name: 'sp_get_openingdate',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_get_remaining_entries',
    label:          'Sp Get Remaining Entries',
    report_type:    'procedure',
    procedure_name: 'sp_get_remaining_entries',
    params: [],
  },

  {
    report_name:    'sp_get_vouchernum',
    label:          'Sp Get Vouchernum',
    report_type:    'procedure',
    procedure_name: 'sp_get_vouchernum',
    params: [
      { name: 'ientry_type', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_homenote_delete',
    label:          'Sp Homenote Delete',
    report_type:    'procedure',
    procedure_name: 'sp_homenote_delete',
    params: [
      { name: 'ihome_note_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_homenote_insert',
    label:          'Sp Homenote Insert',
    report_type:    'procedure',
    procedure_name: 'sp_homenote_insert',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'inote_date', type: 'string', default: null },
      { name: 'idate_from', type: 'string', default: null },
      { name: 'idate_to', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_homenote_select',
    label:          'Sp Homenote Select',
    report_type:    'procedure',
    procedure_name: 'sp_homenote_select',
    params: [],
  },

  {
    report_name:    'sp_homenote_select_all',
    label:          'Sp Homenote Select All',
    report_type:    'procedure',
    procedure_name: 'sp_homenote_select_all',
    params: [],
  },

  {
    report_name:    'sp_homenote_update',
    label:          'Sp Homenote Update',
    report_type:    'procedure',
    procedure_name: 'sp_homenote_update',
    params: [
      { name: 'inote_id', type: 'number', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'inote_date', type: 'string', default: null },
      { name: 'idate_from', type: 'string', default: null },
      { name: 'idate_to', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_import_data',
    label:          'Sp Import Data',
    report_type:    'procedure',
    procedure_name: 'sp_import_data',
    params: [
      { name: 'dbname', type: 'string', default: null },
      { name: 'ist_date', type: 'string', default: null },
      { name: 'ien_date', type: 'string', default: null },
      { name: 'imm_ID', type: 'string', default: null },
      { name: 'imy_id', type: 'number', default: null },
      { name: 'iyr_id', type: 'number', default: null },
      { name: 'istate', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_insert_closing',
    label:          'Sp Insert Closing',
    report_type:    'procedure',
    procedure_name: 'sp_insert_closing',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iquantity', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_insert_closing_mix',
    label:          'Sp Insert Closing Mix',
    report_type:    'procedure',
    procedure_name: 'sp_insert_closing_mix',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iquantity_sewa', type: 'number', default: null },
      { name: 'iquantity_kharida', type: 'number', default: null },
      { name: 'iquantity_mix', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_insert_transfer',
    label:          'Sp Insert Transfer',
    report_type:    'procedure',
    procedure_name: 'sp_insert_transfer',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'itarget_mm_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'itarget_item_id', type: 'number', default: null },
      { name: 'iquantity', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_item_delete',
    label:          'Sp Item Delete',
    report_type:    'procedure',
    procedure_name: 'sp_item_delete',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_item_insert',
    label:          'Sp Item Insert',
    report_type:    'procedure',
    procedure_name: 'sp_item_insert',
    params: [
      { name: 'iitem_name', type: 'string', default: null },
      { name: 'iitem_name_eng', type: 'string', default: null },
      { name: 'iitem_category_id', type: 'number', default: null },
      { name: 'iitem_subcategory_id', type: 'number', default: null },
      { name: 'iunit', type: 'string', default: null },
      { name: 'imin_qty_sm', type: 'number', default: null },
      { name: 'imin_qty_md', type: 'number', default: null },
      { name: 'imin_qty_lg', type: 'number', default: null },
      { name: 'iactive', type: 'boolean', default: null },
      { name: 'iconfirm', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_item_select',
    label:          'Sp Item Select',
    report_type:    'procedure',
    procedure_name: 'sp_item_select',
    params: [],
  },

  {
    report_name:    'sp_item_select_all',
    label:          'Sp Item Select All',
    report_type:    'procedure',
    procedure_name: 'sp_item_select_all',
    params: [],
  },

  {
    report_name:    'sp_item_select_fromcategory',
    label:          'Sp Item Select Fromcategory',
    report_type:    'procedure',
    procedure_name: 'sp_item_select_fromcategory',
    params: [
      { name: 'icategory_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_item_select_fromsubcategory',
    label:          'Sp Item Select Fromsubcategory',
    report_type:    'procedure',
    procedure_name: 'sp_item_select_fromsubcategory',
    params: [
      { name: 'isub_category_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_item_select_mmusewise',
    label:          'Sp Item Select Mmusewise',
    report_type:    'procedure',
    procedure_name: 'sp_item_select_mmusewise',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_item_update',
    label:          'Sp Item Update',
    report_type:    'procedure',
    procedure_name: 'sp_item_update',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iitem_name', type: 'string', default: null },
      { name: 'iitem_name_eng', type: 'string', default: null },
      { name: 'iitem_category_id', type: 'number', default: null },
      { name: 'iitem_subcategory_id', type: 'number', default: null },
      { name: 'iunit', type: 'string', default: null },
      { name: 'imin_qty_sm', type: 'number', default: null },
      { name: 'imin_qty_md', type: 'number', default: null },
      { name: 'imin_qty_lg', type: 'number', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_jawakdetail_fordistribution',
    label:          'Sp Jawakdetail Fordistribution',
    report_type:    'procedure',
    procedure_name: 'sp_jawakdetail_fordistribution',
    params: [
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iref_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_jawaktype_delete',
    label:          'Sp Jawaktype Delete',
    report_type:    'procedure',
    procedure_name: 'sp_jawaktype_delete',
    params: [
      { name: 'ijawak_type_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_jawaktype_insert',
    label:          'Sp Jawaktype Insert',
    report_type:    'procedure',
    procedure_name: 'sp_jawaktype_insert',
    params: [
      { name: 'ijawak_type_hin', type: 'string', default: null },
      { name: 'ijawak_type_eng', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_jawaktype_select',
    label:          'Sp Jawaktype Select',
    report_type:    'procedure',
    procedure_name: 'sp_jawaktype_select',
    params: [],
  },

  {
    report_name:    'sp_jawaktype_update',
    label:          'Sp Jawaktype Update',
    report_type:    'procedure',
    procedure_name: 'sp_jawaktype_update',
    params: [
      { name: 'ijawak_type_id', type: 'number', default: null },
      { name: 'ijawak_type_hin', type: 'string', default: null },
      { name: 'ijawak_type_eng', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_jawak_insert',
    label:          'Sp Jawak Insert',
    report_type:    'procedure',
    procedure_name: 'sp_jawak_insert',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'isource_mm_id', type: 'number', default: null },
      { name: 'ientry_type', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iprice', type: 'number', default: null },
      { name: 'iaawak_ref_id', type: 'string', default: null },
      { name: 'iquantity', type: 'number', default: null },
      { name: 'ijawak_mm_id', type: 'number', default: null },
      { name: 'isewadhari_id', type: 'number', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'ijawak_type_id', type: 'number', default: null },
      { name: 'idescription', type: 'string', default: null },
      { name: 'ibthighlight', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_jawak_update',
    label:          'Sp Jawak Update',
    report_type:    'procedure',
    procedure_name: 'sp_jawak_update',
    params: [
      { name: 'iid', type: 'string', default: null },
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'string', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'ijawak_ref_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iquantity', type: 'number', default: null },
      { name: 'iprice', type: 'number', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'ijawak_mm_id', type: 'number', default: null },
      { name: 'ijawak_type_id', type: 'number', default: null },
      { name: 'idescription', type: 'string', default: null },
      { name: 'ibt_highlight', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_jawak_voucher_select',
    label:          'Sp Jawak Voucher Select',
    report_type:    'procedure',
    procedure_name: 'sp_jawak_voucher_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_mm_delete',
    label:          'Sp Mm Delete',
    report_type:    'procedure',
    procedure_name: 'sp_mm_delete',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_mm_insert',
    label:          'Sp Mm Insert',
    report_type:    'procedure',
    procedure_name: 'sp_mm_insert',
    params: [
      { name: 'imm_name', type: 'string', default: null },
      { name: 'imm_name_hin', type: 'string', default: null },
      { name: 'imm_code', type: 'string', default: null },
      { name: 'imm_type', type: 'string', default: null },
      { name: 'imm_state', type: 'string', default: null },
      { name: 'iparent_mm_id', type: 'number', default: null },
      { name: 'iopening_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_mm_only',
    label:          'Sp Mm Only',
    report_type:    'procedure',
    procedure_name: 'sp_mm_only',
    params: [],
  },

  {
    report_name:    'sp_mm_only_active',
    label:          'Sp Mm Only Active',
    report_type:    'procedure',
    procedure_name: 'sp_mm_only_active',
    params: [],
  },

  {
    report_name:    'sp_mm_select',
    label:          'Sp Mm Select',
    report_type:    'procedure',
    procedure_name: 'sp_mm_select',
    params: [],
  },

  {
    report_name:    'sp_mm_selectkhet',
    label:          'Sp Mm Selectkhet',
    report_type:    'procedure',
    procedure_name: 'sp_mm_selectkhet',
    params: [],
  },

  {
    report_name:    'sp_mm_select_all',
    label:          'Sp Mm Select All',
    report_type:    'procedure',
    procedure_name: 'sp_mm_select_all',
    params: [],
  },

  {
    report_name:    'sp_mm_select_statewise',
    label:          'Sp Mm Select Statewise',
    report_type:    'procedure',
    procedure_name: 'sp_mm_select_statewise',
    params: [
      { name: 'istate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_mm_select_toadd_entrysar',
    label:          'Sp Mm Select Toadd Entrysar',
    report_type:    'procedure',
    procedure_name: 'sp_mm_select_toadd_entrysar',
    params: [
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_mm_update',
    label:          'Sp Mm Update',
    report_type:    'procedure',
    procedure_name: 'sp_mm_update',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'imm_name', type: 'string', default: null },
      { name: 'imm_name_hin', type: 'string', default: null },
      { name: 'imm_code', type: 'string', default: null },
      { name: 'imm_type', type: 'string', default: null },
      { name: 'imm_state', type: 'string', default: null },
      { name: 'iparent_mm_id', type: 'number', default: null },
      { name: 'iopening_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_aawakjawak',
    label:          'Sp Monthly Report Aawakjawak',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_aawakjawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_ids', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_item',
    label:          'Sp Monthly Report Item',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_item',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_itemwise',
    label:          'Sp Monthly Report Itemwise',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_itemwise',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_item_stock',
    label:          'Sp Monthly Report Item Stock',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_item_stock',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_limited',
    label:          'Sp Monthly Report Limited',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_limited',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_stock',
    label:          'Sp Monthly Report Stock',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_stock',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iitem_ids', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_monthly_report_stock_chk',
    label:          'Sp Monthly Report Stock Chk',
    report_type:    'procedure',
    procedure_name: 'sp_monthly_report_stock_chk',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_note_delete',
    label:          'Sp Note Delete',
    report_type:    'procedure',
    procedure_name: 'sp_note_delete',
    params: [
      { name: 'inote_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_note_insert',
    label:          'Sp Note Insert',
    report_type:    'procedure',
    procedure_name: 'sp_note_insert',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'inote_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_note_select',
    label:          'Sp Note Select',
    report_type:    'procedure',
    procedure_name: 'sp_note_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_note_select_forreport',
    label:          'Sp Note Select Forreport',
    report_type:    'procedure',
    procedure_name: 'sp_note_select_forreport',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istart_date', type: 'string', default: null },
      { name: 'iend_date', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_note_update',
    label:          'Sp Note Update',
    report_type:    'procedure',
    procedure_name: 'sp_note_update',
    params: [
      { name: 'inote_id', type: 'number', default: null },
      { name: 'inote', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'inote_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_openingstock_aawakjawakbook',
    label:          'Sp Openingstock Aawakjawakbook',
    report_type:    'procedure',
    procedure_name: 'sp_openingstock_aawakjawakbook',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_pbks_delete',
    label:          'Sp Pbks Delete',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_delete',
    params: [
      { name: 'ipbks_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_pbks_insert',
    label:          'Sp Pbks Insert',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_insert',
    params: [
      { name: 'iname_hin', type: 'string', default: null },
      { name: 'iname_eng', type: 'string', default: null },
      { name: 'ifather_name', type: 'string', default: null },
      { name: 'iage', type: 'number', default: null },
      { name: 'iaddress', type: 'string', default: null },
      { name: 'iclass_id', type: 'number', default: null },
      { name: 'ibhatti_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_pbks_select',
    label:          'Sp Pbks Select',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_select',
    params: [],
  },

  {
    report_name:    'sp_pbks_select_all',
    label:          'Sp Pbks Select All',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_select_all',
    params: [],
  },

  {
    report_name:    'sp_pbks_select_used',
    label:          'Sp Pbks Select Used',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_select_used',
    params: [
      { name: 'istart_date', type: 'string', default: null },
      { name: 'iend_date', type: 'string', default: null },
      { name: 'imm_ids', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_pbks_update',
    label:          'Sp Pbks Update',
    report_type:    'procedure',
    procedure_name: 'sp_pbks_update',
    params: [
      { name: 'ipbks_id', type: 'number', default: null },
      { name: 'iname_hin', type: 'string', default: null },
      { name: 'iname_eng', type: 'string', default: null },
      { name: 'ifather_name', type: 'string', default: null },
      { name: 'iage', type: 'number', default: null },
      { name: 'iaddress', type: 'string', default: null },
      { name: 'iclass_id', type: 'number', default: null },
      { name: 'ibhatti_date', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_report_aawak_jawak',
    label:          'Sp Report Aawak Jawak',
    report_type:    'procedure',
    procedure_name: 'sp_report_aawak_jawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_report_sewa_aawak',
    label:          'Sp Report Sewa Aawak',
    report_type:    'procedure',
    procedure_name: 'sp_report_sewa_aawak',
    params: [
      { name: 'strmm_ids', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'ipbks', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_searchjawak_dateitempktnum',
    label:          'Sp Searchjawak Dateitempktnum',
    report_type:    'procedure',
    procedure_name: 'sp_searchjawak_dateitempktnum',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_searchjawak_dateitempktnumdescription',
    label:          'Sp Searchjawak Dateitempktnumdescription',
    report_type:    'procedure',
    procedure_name: 'sp_searchjawak_dateitempktnumdescription',
    params: [
      { name: 'strmm_id', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'strdescription', type: 'string', default: null },
      { name: 'strsewadhari_ids', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_search_dateitempktnum',
    label:          'Sp Search Dateitempktnum',
    report_type:    'procedure',
    procedure_name: 'sp_search_dateitempktnum',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_search_dateitempktnumdescription',
    label:          'Sp Search Dateitempktnumdescription',
    report_type:    'procedure',
    procedure_name: 'sp_search_dateitempktnumdescription',
    params: [
      { name: 'strmm_id', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'strdescription', type: 'string', default: null },
      { name: 'strsewadhari_ids', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_selectnote_for_description',
    label:          'Sp Selectnote For Description',
    report_type:    'procedure',
    procedure_name: 'sp_selectnote_for_description',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_select_aawak_type',
    label:          'Sp Select Aawak Type',
    report_type:    'procedure',
    procedure_name: 'sp_select_aawak_type',
    params: [],
  },

  {
    report_name:    'sp_select_automatic_aawak',
    label:          'Sp Select Automatic Aawak',
    report_type:    'procedure',
    procedure_name: 'sp_select_automatic_aawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_select_automatic_jawak',
    label:          'Sp Select Automatic Jawak',
    report_type:    'procedure',
    procedure_name: 'sp_select_automatic_jawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istore_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_select_closing_date',
    label:          'Sp Select Closing Date',
    report_type:    'procedure',
    procedure_name: 'sp_select_closing_date',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_select_entrysar',
    label:          'Sp Select Entrysar',
    report_type:    'procedure',
    procedure_name: 'sp_select_entrysar',
    params: [
      { name: 'iyear', type: 'number', default: null },
      { name: 'istates', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_select_latest_entryofmm',
    label:          'Sp Select Latest Entryofmm',
    report_type:    'procedure',
    procedure_name: 'sp_select_latest_entryofmm',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'dtdate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_select_maxdateofeachmm',
    label:          'Sp Select Maxdateofeachmm',
    report_type:    'procedure',
    procedure_name: 'sp_select_maxdateofeachmm',
    params: [],
  },

  {
    report_name:    'sp_select_selected_aawak_type',
    label:          'Sp Select Selected Aawak Type',
    report_type:    'procedure',
    procedure_name: 'sp_select_selected_aawak_type',
    params: [],
  },

  {
    report_name:    'sp_sewadhari_delete',
    label:          'Sp Sewadhari Delete',
    report_type:    'procedure',
    procedure_name: 'sp_sewadhari_delete',
    params: [
      { name: 'isewadhari_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_sewadhari_insert',
    label:          'Sp Sewadhari Insert',
    report_type:    'procedure',
    procedure_name: 'sp_sewadhari_insert',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate_from', type: 'string', default: null },
      { name: 'idate_to', type: 'string', default: null },
      { name: 'isewadhari_1', type: 'string', default: null },
      { name: 'isewadhari_2', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_sewadhari_select',
    label:          'Sp Sewadhari Select',
    report_type:    'procedure',
    procedure_name: 'sp_sewadhari_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'idate_from', type: 'string', default: null },
      { name: 'idate_to', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_sewadhari_select_all',
    label:          'Sp Sewadhari Select All',
    report_type:    'procedure',
    procedure_name: 'sp_sewadhari_select_all',
    params: [
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_sewadhari_update',
    label:          'Sp Sewadhari Update',
    report_type:    'procedure',
    procedure_name: 'sp_sewadhari_update',
    params: [
      { name: 'isewadhari_id', type: 'number', default: null },
      { name: 'idate_from', type: 'string', default: null },
      { name: 'idate_to', type: 'string', default: null },
      { name: 'isewadhari_1', type: 'string', default: null },
      { name: 'isewadhari_2', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_state_select',
    label:          'Sp State Select',
    report_type:    'procedure',
    procedure_name: 'sp_state_select',
    params: [],
  },

  {
    report_name:    'sp_stockregister_select_aawakdetail',
    label:          'Sp Stockregister Select Aawakdetail',
    report_type:    'procedure',
    procedure_name: 'sp_stockregister_select_aawakdetail',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'itype_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stockregister_select_aawakdetail_foraawak',
    label:          'Sp Stockregister Select Aawakdetail Foraawak',
    report_type:    'procedure',
    procedure_name: 'sp_stockregister_select_aawakdetail_foraawak',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'iaawak_type_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stockregister_select_aawakdetail_old',
    label:          'Sp Stockregister Select Aawakdetail Old',
    report_type:    'procedure',
    procedure_name: 'sp_stockregister_select_aawakdetail_old',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_stockregister_select_aawakdetail_old1',
    label:          'Sp Stockregister Select Aawakdetail Old1',
    report_type:    'procedure',
    procedure_name: 'sp_stockregister_select_aawakdetail_old1',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'ijawak_type_id', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stock_allmm',
    label:          'Sp Stock Allmm',
    report_type:    'procedure',
    procedure_name: 'sp_stock_allmm',
    params: [
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'istate', type: 'string', default: null },
      { name: 'iitemids', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stock_distribution',
    label:          'Sp Stock Distribution',
    report_type:    'procedure',
    procedure_name: 'sp_stock_distribution',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_stock_distribution_all',
    label:          'Sp Stock Distribution All',
    report_type:    'procedure',
    procedure_name: 'sp_stock_distribution_all',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stock_distribution_mm_list',
    label:          'Sp Stock Distribution Mm List',
    report_type:    'procedure',
    procedure_name: 'sp_stock_distribution_mm_list',
    params: [
      { name: 'idescription_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_stock_list_forbook',
    label:          'Sp Stock List Forbook',
    report_type:    'procedure',
    procedure_name: 'sp_stock_list_forbook',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'strItem_ids', type: 'string', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stock_list_itemwise',
    label:          'Sp Stock List Itemwise',
    report_type:    'procedure',
    procedure_name: 'sp_stock_list_itemwise',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_stock_list_mmwise',
    label:          'Sp Stock List Mmwise',
    report_type:    'procedure',
    procedure_name: 'sp_stock_list_mmwise',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_subcategory_delete',
    label:          'Sp Subcategory Delete',
    report_type:    'procedure',
    procedure_name: 'sp_subcategory_delete',
    params: [
      { name: 'isubcategory_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_subcategory_insert',
    label:          'Sp Subcategory Insert',
    report_type:    'procedure',
    procedure_name: 'sp_subcategory_insert',
    params: [
      { name: 'isubcategory_name', type: 'string', default: null },
      { name: 'isubcategory_name_eng', type: 'string', default: null },
      { name: 'icategory_id', type: 'number', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_subcategory_select',
    label:          'Sp Subcategory Select',
    report_type:    'procedure',
    procedure_name: 'sp_subcategory_select',
    params: [
      { name: 'icategory_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_subcategory_select_all',
    label:          'Sp Subcategory Select All',
    report_type:    'procedure',
    procedure_name: 'sp_subcategory_select_all',
    params: [],
  },

  {
    report_name:    'sp_subcategory_update',
    label:          'Sp Subcategory Update',
    report_type:    'procedure',
    procedure_name: 'sp_subcategory_update',
    params: [
      { name: 'isubcategory_id', type: 'number', default: null },
      { name: 'isubcategory_name', type: 'string', default: null },
      { name: 'isubcategory_name_eng', type: 'string', default: null },
      { name: 'icategory_id', type: 'number', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_total_aj_report',
    label:          'Sp Total Aj Report',
    report_type:    'procedure',
    procedure_name: 'sp_total_aj_report',
    params: [
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'strtype', type: 'string', default: null },
      { name: 'strentry_type', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_transfer_delete',
    label:          'Sp Transfer Delete',
    report_type:    'procedure',
    procedure_name: 'sp_transfer_delete',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_transfer_update',
    label:          'Sp Transfer Update',
    report_type:    'procedure',
    procedure_name: 'sp_transfer_update',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'isl_no', type: 'number', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'isource_mm_id', type: 'number', default: null },
      { name: 'isource_item_id', type: 'number', default: null },
      { name: 'iquantity', type: 'number', default: null },
      { name: 'itarget_mm_id', type: 'number', default: null },
      { name: 'itarget_item_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_transfer_voucher_getdetail',
    label:          'Sp Transfer Voucher Getdetail',
    report_type:    'procedure',
    procedure_name: 'sp_transfer_voucher_getdetail',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_transfer_voucher_select',
    label:          'Sp Transfer Voucher Select',
    report_type:    'procedure',
    procedure_name: 'sp_transfer_voucher_select',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
      { name: 'iitem_id', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_unit_delete',
    label:          'Sp Unit Delete',
    report_type:    'procedure',
    procedure_name: 'sp_unit_delete',
    params: [
      { name: 'iunit_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_unit_insert',
    label:          'Sp Unit Insert',
    report_type:    'procedure',
    procedure_name: 'sp_unit_insert',
    params: [
      { name: 'iunit_name', type: 'string', default: null },
      { name: 'iunit_short_name', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_unit_select',
    label:          'Sp Unit Select',
    report_type:    'procedure',
    procedure_name: 'sp_unit_select',
    params: [],
  },

  {
    report_name:    'sp_unit_selectall',
    label:          'Sp Unit Selectall',
    report_type:    'procedure',
    procedure_name: 'sp_unit_selectall',
    params: [],
  },

  {
    report_name:    'sp_unit_update',
    label:          'Sp Unit Update',
    report_type:    'procedure',
    procedure_name: 'sp_unit_update',
    params: [
      { name: 'iunit_id', type: 'number', default: null },
      { name: 'iunit_name', type: 'string', default: null },
      { name: 'iunit_short_name', type: 'string', default: null },
      { name: 'iactive', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_update_entrysar',
    label:          'Sp Update Entrysar',
    report_type:    'procedure',
    procedure_name: 'sp_update_entrysar',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'imonth', type: 'number', default: null },
      { name: 'strtype', type: 'string', default: null },
      { name: 'iflag', type: 'boolean', default: null },
      { name: 'btype', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_update_entrysar_mm',
    label:          'Sp Update Entrysar Mm',
    report_type:    'procedure',
    procedure_name: 'sp_update_entrysar_mm',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'iflag', type: 'boolean', default: null },
      { name: 'btype', type: 'boolean', default: null },
    ],
  },

  {
    report_name:    'sp_user_check',
    label:          'Sp User Check',
    report_type:    'procedure',
    procedure_name: 'sp_user_check',
    params: [
      { name: 'iusername', type: 'string', default: null },
      { name: 'ipassword', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_verify_notverifiedaawak',
    label:          'Sp Verify Notverifiedaawak',
    report_type:    'procedure',
    procedure_name: 'sp_verify_notverifiedaawak',
    params: [
      { name: 'iid', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_vouchercommondetail_fromvoucherno',
    label:          'Sp Vouchercommondetail Fromvoucherno',
    report_type:    'procedure',
    procedure_name: 'sp_vouchercommondetail_fromvoucherno',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_aawak_update',
    label:          'Sp Voucher Aawak Update',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_aawak_update',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'iaawak_source', type: 'string', default: null },
      { name: 'iaawak_mm_id', type: 'number', default: null },
      { name: 'isewadhari_id', type: 'number', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_delete',
    label:          'Sp Voucher Delete',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_delete',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_getdetail',
    label:          'Sp Voucher Getdetail',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_getdetail',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'ientry_type', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_jawak_update',
    label:          'Sp Voucher Jawak Update',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_jawak_update',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'ijawak_detail', type: 'string', default: null },
      { name: 'ijawak_mm_id', type: 'number', default: null },
      { name: 'isewadhari_id', type: 'number', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_select',
    label:          'Sp Voucher Select',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_select',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'ientry_type', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp_voucher_transfer_update',
    label:          'Sp Voucher Transfer Update',
    report_type:    'procedure',
    procedure_name: 'sp_voucher_transfer_update',
    params: [
      { name: 'ivoucher_no', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'ipkt_num', type: 'string', default: null },
      { name: 'isource_mm_id', type: 'number', default: null },
      { name: 'itarget_mm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'sp_yearly_reports',
    label:          'Sp Yearly Reports',
    report_type:    'procedure',
    procedure_name: 'sp_yearly_reports',
    params: [
      { name: 'iyear', type: 'number', default: null },
      { name: 'imm_id', type: 'number', default: null },
      { name: 'strItemIds', type: 'string', default: null },
      { name: 'strType', type: 'string', default: null },
    ],
  },

  {
    report_name:    'sp__select_aawakdetail_fordistribution',
    label:          'Sp  Select Aawakdetail Fordistribution',
    report_type:    'procedure',
    procedure_name: 'sp__select_aawakdetail_fordistribution',
    params: [
      { name: 'iitem_id', type: 'number', default: null },
      { name: 'itype_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'test',
    label:          'Test',
    report_type:    'procedure',
    procedure_name: 'test',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'istartdate', type: 'string', default: null },
      { name: 'ienddate', type: 'string', default: null },
    ],
  },

  {
    report_name:    'update_partial_data',
    label:          'Update Partial Data',
    report_type:    'procedure',
    procedure_name: 'update_partial_data',
    params: [
      { name: 'dbname', type: 'string', default: null },
      { name: 'idate', type: 'string', default: null },
      { name: 'imm_ID', type: 'number', default: null },
    ],
  },

  {
    report_name:    'yearly_jawak_report_mm_wise',
    label:          'Yearly Jawak Report Mm Wise',
    report_type:    'procedure',
    procedure_name: 'yearly_jawak_report_mm_wise',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'imonth', type: 'string', default: null },
      { name: 'ijawak_mm_id', type: 'number', default: null },
    ],
  },

  {
    report_name:    'yearly_report_aawak_jawak',
    label:          'Yearly Report Aawak Jawak',
    report_type:    'procedure',
    procedure_name: 'yearly_report_aawak_jawak',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'itype', type: 'string', default: null },
    ],
  },

  {
    report_name:    'yearly_report_bulk_aj',
    label:          'Yearly Report Bulk Aj',
    report_type:    'procedure',
    procedure_name: 'yearly_report_bulk_aj',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'itype', type: 'string', default: null },
    ],
  },

  {
    report_name:    'yearly_report_bulk_u',
    label:          'Yearly Report Bulk U',
    report_type:    'procedure',
    procedure_name: 'yearly_report_bulk_u',
    params: [
      { name: 'imm_id1', type: 'number', default: null },
      { name: 'imm_id2', type: 'number', default: null },
      { name: 'imm_id3', type: 'number', default: null },
      { name: 'imm_id4', type: 'number', default: null },
      { name: 'imm_id5', type: 'number', default: null },
      { name: 'imm_id6', type: 'number', default: null },
      { name: 'imm_id7', type: 'number', default: null },
      { name: 'imm_id8', type: 'number', default: null },
      { name: 'imm_id9', type: 'number', default: null },
      { name: 'imm_id10', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'yearly_report_price_aj',
    label:          'Yearly Report Price Aj',
    report_type:    'procedure',
    procedure_name: 'yearly_report_price_aj',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
      { name: 'itype', type: 'string', default: null },
    ],
  },

  {
    report_name:    'yearly_report_price_u',
    label:          'Yearly Report Price U',
    report_type:    'procedure',
    procedure_name: 'yearly_report_price_u',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'yearly_report_sar',
    label:          'Yearly Report Sar',
    report_type:    'procedure',
    procedure_name: 'yearly_report_sar',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

  {
    report_name:    'yearly_report_used',
    label:          'Yearly Report Used',
    report_type:    'procedure',
    procedure_name: 'yearly_report_used',
    params: [
      { name: 'imm_id', type: 'number', default: null },
      { name: 'iyear', type: 'number', default: null },
    ],
  },

];