// database/schema.js
// Auto-generated by: npx sutramcore-mysql import
// Review joins{} — hasMany and manyToMany must be added manually
'use strict';

const { defineTable, col } = require('sutramcore');

module.exports = {

  ...defineTable('aawak_type', {
    aawak_type_id       : col.id(),
    aawak_type_hin      : col.string(),
    aawak_type_eng      : col.string(),
    date_created        : col.string(),
    bt_active           : col.boolean(),
  }),

  ...defineTable('category', {
    category_id         : col.id(),
    category_name       : col.string().required(),
    category_name_eng   : col.string(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('description', {
    description_id      : col.id(),
    item_id             : col.number(),
    aawak_type_id       : col.number(),
    description_hin     : col.string(),
    description_eng     : col.string(),
    aawak_date          : col.string(),
    note                : col.json(),
    active              : col.boolean(),
  }),

  ...defineTable('entry_sar', {
    mm_id               : col.number().required(),
    year                : col.number().required(),
    months              : col.number().required(),
    bt_ak               : col.boolean().default(0),
    bt_jk               : col.boolean().default(0),
    bt_bct              : col.boolean().default(0),
    ak_date             : col.string(),
    jk_date             : col.string(),
    bct_date            : col.string(),
    mm_active           : col.boolean().default(1),
    entry_date          : col.string().default('CURRENT_TIMESTAMP'),
    es_type             : col.boolean().default(0),
  }),

  ...defineTable('home_note', {
    home_note_id        : col.id(),
    mm_id               : col.number(),
    note_date           : col.string(),
    note_detail         : col.json(),
    date_from           : col.string(),
    date_to             : col.string(),
    bt_active           : col.boolean().default(1),
  }),

  ...defineTable('item', {
    item_id             : col.id(),
    item_name           : col.string().default('NOT NULL'),
    item_name_eng       : col.string(),
    item_category_id    : col.ref('category.category_id', {
      as: 'category', select: ['category_name'],
    }),
    item_subcategory_id : col.number(),
    unit                : col.string(),
    min_qty_lg          : col.number().default(0),
    min_qty_md          : col.number().default(0),
    min_qty_sm          : col.number().default(0),
    active              : col.boolean().default(1),
    sq_no               : col.number(),
    rate_2017           : col.number().default(0),
  }),

  ...defineTable('jawak_type', {
    jawak_type_id       : col.id(),
    jawak_type_eng      : col.string(),
    jawak_type_hin      : col.string(),
    date_created        : col.string().default('CURRENT_TIMESTAMP'),
    bt_active           : col.boolean().default(1),
  }),

  ...defineTable('mm_list', {
    mm_id               : col.id(),
    mm_code             : col.string(),
    mm_name             : col.string(),
    mm_name_hin         : col.string(),
    mm_type             : col.string(),
    mm_state            : col.string(),
    opening_date        : col.string(),
    parent_mm_id        : col.number(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('note', {
    note_id             : col.id(),
    note                : col.json(),
    mm_id               : col.number(),
    note_date           : col.string(),
    entry_date          : col.string().default('CURRENT_TIMESTAMP'),
    active              : col.boolean().default(1),
  }),

  ...defineTable('pbks', {
    pbks_id             : col.id(),
    name_hin            : col.string(),
    name_eng            : col.string(),
    father_name         : col.string(),
    age                 : col.number(),
    address             : col.string(),
    class               : col.number(),
    bhatti_date         : col.string(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('pbks_mount', {
    pbks_id             : col.id(),
    name_hin            : col.string(),
    name_eng            : col.string(),
    father_name         : col.string(),
    age                 : col.number(),
    address             : col.string(),
    class               : col.number(),
    bhatti_date         : col.string(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('ref', {
    id                  : col.id(),
    main_id             : col.number(),
    ref_id              : col.number(),
    db_name             : col.string(),
    date                : col.string().default('CURRENT_TIMESTAMP'),
  }),

  ...defineTable('sewadhari', {
    sewadhari_id        : col.id(),
    mm_id               : col.number(),
    date_from           : col.string(),
    date_to             : col.string(),
    sewadhari_1         : col.string(),
    sewadhari_2         : col.string(),
    active              : col.boolean(),
  }),

  ...defineTable('state', {
    state_id            : col.id(),
    state_name          : col.string(),
    bt_active           : col.boolean().default(1),
  }),

  ...defineTable('stockregister', {
    id                  : col.id(),
    voucher_no          : col.string(),
    voucher_num         : col.number(),
    sl_no               : col.number(),
    mm_id               : col.ref('mm_list.mm_id', {
      as: 'mm_list', select: ['mm_code'],
    }),
    entry_type          : col.string(),
    date                : col.string(),
    item_id             : col.ref('item.item_id', {
      as: 'item', select: ['item_name'],
    }),
    item_name           : col.string(),
    company_name        : col.string(),
    quantity            : col.number(),
    source_mm_id        : col.number(),
    price               : col.string(),
    aawak_type          : col.ref('aawak_type.aawak_type_id', {
      as: 'aawak_type', select: ['aawak_type_hin'],
    }),
    aawak_source        : col.string(),
    aawak_description   : col.string(),
    aawak_detail        : col.string(),
    aawak_mm_id         : col.number(),
    sewadhari_id        : col.number(),
    jawak_mm_id         : col.number(),
    jawak_mm_name       : col.string(),
    jawak_detail        : col.string(),
    jawak_type_id       : col.ref('jawak_type.jawak_type_id', {
      as: 'jawak_type', select: ['jawak_type_hin'],
    }),
    ref_id              : col.number(),
    qty_remaining       : col.number(),
    pkt_num             : col.string(),
    total_consumption   : col.number(),
    entry_date          : col.string().default('CURRENT_TIMESTAMP'),
    bt_active           : col.boolean().default(1),
    bt_highlight        : col.boolean().default(0),
    bt_check            : col.boolean().default(0),
    bt_auto             : col.boolean().default(0),
    bt_check_voucher    : col.boolean().default(0),
    bt_import           : col.boolean(),
    db_name             : col.string(),
  }),

  ...defineTable('stockregister1', {
    id                  : col.number().required(),
    voucher_no          : col.string(),
    voucher_num         : col.number(),
    sl_no               : col.number(),
    mm_id               : col.number(),
    entry_type          : col.string(),
    date                : col.string(),
    item_id             : col.number(),
    item_name           : col.string(),
    company_name        : col.string(),
    quantity            : col.number(),
    source_mm_id        : col.number(),
    price               : col.string(),
    aawak_type          : col.number(),
    aawak_source        : col.string(),
    aawak_description   : col.string(),
    aawak_detail        : col.string(),
    aawak_mm_id         : col.number(),
    sewadhari_id        : col.number(),
    jawak_mm_id         : col.number(),
    jawak_mm_name       : col.string(),
    jawak_detail        : col.string(),
    jawak_type_id       : col.number(),
    ref_id              : col.number(),
    qty_remaining       : col.number(),
    pkt_num             : col.string(),
    total_consumption   : col.number(),
    entry_date          : col.string().default('CURRENT_TIMESTAMP'),
    bt_active           : col.boolean(),
    bt_highlight        : col.boolean(),
    bt_check            : col.boolean(),
    bt_auto             : col.boolean(),
    bt_check_voucher    : col.boolean(),
    voucher_num_new     : col.number(),
    voucher_no_new      : col.string(),
  }),

  ...defineTable('subcategory', {
    subcategory_id      : col.id(),
    category_id         : col.ref('category.category_id', {
      as: 'category', select: ['category_name'],
    }),
    subcategory_name    : col.string().required(),
    subcategory_name_eng: col.string(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('tempitem', {
    item_id             : col.number(),
    item_name_hin       : col.string(),
    item_name           : col.string(),
    item_name_eng       : col.string(),
    unit                : col.string(),
    category_name       : col.string(),
    closing_date        : col.string(),
    total_quantity_available: col.number(),
    min_quantity        : col.number(),
  }),

  ...defineTable('tempmonth', {
    id                  : col.number(),
    month_name          : col.string(),
  }),

  ...defineTable('temprecord', {
    entry_type          : col.string(),
    idate               : col.string(),
    item_id             : col.number(),
    item_name           : col.string(),
    mm_name             : col.string(),
    category_id         : col.number(),
    category_name       : col.string(),
    aawak_quantity      : col.number(),
    jawak_quantity      : col.number(),
    closing_quantity    : col.number(),
    itype_id            : col.number(),
    itype_name          : col.string(),
    pkt_num             : col.string(),
    ajmm_id             : col.number(),
    ajmm_name           : col.string(),
    unit                : col.string(),
    price               : col.string(),
    amount              : col.string(),
    jawak_detail        : col.string(),
    jawak_mm_name       : col.string(),
    description         : col.string(),
    aawak_source        : col.number(),
  }),

  ...defineTable('unit', {
    unit_id             : col.id(),
    unit_name           : col.string(),
    unit_short_name     : col.string(),
    active              : col.boolean().default(1),
  }),

  ...defineTable('user', {
    userid              : col.id(),
    mmid                : col.number(),
    username            : col.string().required(),
    password            : col.string().required(),
    date_created        : col.string(),
  }),

  ...defineTable('your_table_name', {
    id                  : col.id(),
    mm_id               : col.number(),
    entry_type          : col.string(),
    date                : col.string(),
    quantity            : col.number(),
    item_id             : col.number(),
  }),

  ...defineTable('tempItem', {
    item_id             : col.number(),
  }),

  ...defineTable('tempRecord', {
    entry_type          : col.string(),
  }),

  ...defineTable('tempMonth', {
    id                  : col.number(),
  }),

  ...defineTable('temp', {
    mm_id               : col.string(),
  }),

};