// src/cli/ReportsGenerator.js
// ─────────────────────────────────────────────────────────────
// Generates reports.js from parsed stored procedures.
// ─────────────────────────────────────────────────────────────

'use strict';

class ReportsGenerator {

    generate(procedures) {
        if (!procedures.length) {
            return {
                code: `// database/reports.js\n// No stored procedures found.\nmodule.exports = [];\n`,
                warnings: [],
            };
        }

        const lines = [];
        lines.push(`// database/reports.js`);
        lines.push(`// Auto-generated by: npx sutramcore-mysql import --reports`);
        lines.push(`// Review: add labels, descriptions, and default param values`);
        lines.push(`'use strict';`);
        lines.push(``);
        lines.push(`module.exports = [`);
        lines.push(``);

        for (const proc of procedures) {
            lines.push(`  {`);
            lines.push(`    report_name:    '${proc.name}',`);
            lines.push(`    label:          '${this._toLabel(proc.name)}',`);
            lines.push(`    report_type:    'procedure',`);
            lines.push(`    procedure_name: '${proc.name}',`);

            if (proc.params.length) {
                lines.push(`    params: [`);
                for (const p of proc.params) {
                    lines.push(`      { name: '${p.name}', type: '${p.type}', default: null },`);
                }
                lines.push(`    ],`);
            } else {
                lines.push(`    params: [],`);
            }

            lines.push(`  },`);
            lines.push(``);
        }

        lines.push(`];`);

        return { code: lines.join('\n'), warnings: [] };
    }

    // snake_case / camelCase → Title Case label
    _toLabel(name) {
        return name
            .replace(/_/g, ' ')
            .replace(/([a-z])([A-Z])/g, '$1 $2')
            .replace(/\b\w/g, c => c.toUpperCase());
    }
}

module.exports = ReportsGenerator;
