// src/cli/SchemaGenerator.js
// ─────────────────────────────────────────────────────────────
// Generates schema.js content from parsed SQL tables.
// ─────────────────────────────────────────────────────────────

'use strict';

class SchemaGenerator {

    generate(tables) {
        // sort by dependency — tables with no FK first
        const sorted = this._sortByDependency(tables);

        const lines = [];
        const warnings = [];

        lines.push(`// database/schema.js`);
        lines.push(`// Auto-generated by: npx sutramcore-mysql import`);
        lines.push(`// Review joins{} — hasMany and manyToMany must be added manually`);
        lines.push(`'use strict';`);
        lines.push(``);
        lines.push(`const { defineTable, col } = require('sutramcore');`);
        lines.push(``);
        lines.push(`module.exports = {`);
        lines.push(``);

        for (const table of sorted) {
            const { code, tableWarnings } = this._generateTable(table, tables);
            lines.push(...code);
            warnings.push(...tableWarnings);
        }

        lines.push(`};`);

        return { code: lines.join('\n'), warnings };
    }

    _generateTable(table, allTables) {
        const { tableName, columns, foreignKeys } = table;
        const warnings = [];
        const lines = [];

        // build FK map for quick lookup
        const fkMap = {};
        for (const fk of foreignKeys) {
            fkMap[fk.column] = fk;
        }

        lines.push(`  ...defineTable('${tableName}', {`);

        for (const col of columns) {
            const fk = fkMap[col.name];

            if (col.isPK) {
                lines.push(`    ${col.name.padEnd(20)}: col.id(),`);
                continue;
            }

            let colExpr = `col.${col.type}()`;

            if (col.isRequired) colExpr += `.required()`;
            if (col.default !== null && col.default !== undefined) {
                const defVal = col.type === 'string'
                    ? `'${col.default}'`
                    : col.default;
                colExpr += `.default(${defVal})`;
            }

            // FK column — add ref
            if (fk) {
                const refTable = this._findTable(fk.refTable, allTables);
                // detect label column — common patterns
                const labelCol = refTable
                    ? this._detectLabelColumn(refTable)
                    : null;

                const selectStr = labelCol ? `['${labelCol}']` : `['*']`;
                const asName    = fk.refTable;

                colExpr = `col.ref('${fk.refTable}.${fk.refColumn}', {`;
                lines.push(`    ${col.name.padEnd(20)}: ${colExpr}`);
                lines.push(`      as: '${asName}', select: ${selectStr},`);
                lines.push(`    }),`);
                continue;
            }

            lines.push(`    ${col.name.padEnd(20)}: ${colExpr},`);
        }

        lines.push(`  }),`);
        lines.push(``);

        return { code: lines, tableWarnings: warnings };
    }

    _findTable(name, allTables) {
        return allTables.find(t => t.tableName === name);
    }

    _detectLabelColumn(table) {
        const nameCols = ['name', 'title', 'label', 'description',
                          'name_en', 'name_hin', 'hin', 'eng',
                          table.tableName + '_name', table.tableName + '_hin'];

        for (const col of table.columns) {
            if (nameCols.includes(col.name.toLowerCase())) return col.name;
        }

        // fallback — first string column that isn't _id
        const strCol = table.columns.find(c => c.type === 'string' && !c.isPK);
        return strCol?.name ?? null;
    }

    _sortByDependency(tables) {
        const sorted  = [];
        const visited = new Set();
        const names   = new Set(tables.map(t => t.tableName));

        const visit = (table) => {
            if (visited.has(table.tableName)) return;

            // visit dependencies first
            for (const fk of table.foreignKeys) {
                if (names.has(fk.refTable) && !visited.has(fk.refTable)) {
                    const dep = tables.find(t => t.tableName === fk.refTable);
                    if (dep) visit(dep);
                }
            }

            visited.add(table.tableName);
            sorted.push(table);
        };

        for (const table of tables) visit(table);
        return sorted;
    }
}

module.exports = SchemaGenerator;
