const express = require('express');
const router = express.Router();


const { dbmodal, sutramDB } = require('../database/db.model');
const db = dbmodal.db;
const BaseTable = require('../database/base.table');

// ── Simple table instances ──
const Prastav = new BaseTable('prastav');
const PrastavJawak = new BaseTable('prastav_jawak');

// ── Prastav main ──────────────────────────────────────────────

// Get all prastav (with joins)
// Optional query params: active, mm_id, item_id, date
router.get('/', (req, res, next) => {
    try {
        const { active, mm_id, item_id, date } = req.query || {};
        const where = {};

        if (active !== undefined) where.active = (active === '1' || active === 1 || active === true || active === 'true') ? 1 : 0;
        if (mm_id !== undefined && mm_id !== '') where.mm_id = Number(mm_id);
        if (item_id !== undefined && item_id !== '') where.item_id = Number(item_id);
        if (date !== undefined && date !== '') where.date = String(date);

        let rows = Prastav.getAll(where);
        
        // Include nested jawaks for each prastav
        rows = rows.map(row => {
            row.jawaks = PrastavJawak.getAll({ prastav_id: row._id });
            return row;
        });

        res.status(200).json({ success: true, result: rows });
    } catch (e) {
        next(e);
    }
});

// Get single prastav by id (with joins + jawaks)
router.get('/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = Prastav.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update prastav
router.post('/', (req, res, next) => {
    try {
        const data = req.body || {};
        delete data.voucher_no;   // auto-generated by DB, never from frontend

        const lines = Array.isArray(data.lines) ? data.lines.filter(l => l.item_id || l.item_subitem_id) : [];

        let resultIds;
        sutramDB.begin();
        try {
            let voucher_no;
            let pIds = [];

            // If updating an existing single prastav (data._id is passed)
            if (data._id && lines.length === 1) {
                const line = lines[0];
                const pId = Number(data._id);
                const prastavData = {
                    ...data,
                    _id: pId,
                    item_id: line.item_id,
                    subitem_id: line.subitem_id || null,
                    unit_id: line.unit_id,
                    qty_needs: line.qty_needs || null,
                    qty: line.qty,
                    bachat: line.bachat || 0,
                    monthly_uses: line.monthly_uses || 0,
                    rate: line.rate || 0,
                    amount: line.amount || 0,
                    description: line.description || null,
                };
                delete prastavData.lines;

                Prastav.updateById(prastavData, pId, false);
                db.prepare(`DELETE FROM prastav_jawak WHERE prastav_id = ?`).run(pId);
                
                const jawaks = Array.isArray(line.jawaks) ? line.jawaks.filter(j => j.source_mm_id && j.qty) : [];
                for (const jw of jawaks) {
                    const jawakData = {
                        prastav_id: pId,
                        date: jw.date || data.date,
                        mm_id: data.mm_id,
                        item_id: jw.item_id || line.item_id,
                        subitem_id: jw.subitem_id || line.subitem_id || null,
                        unit_id: line.unit_id,
                        qty: jw.qty,
                        rate: jw.rate || 0,
                        amount: jw.amount || 0,
                        bori_count: jw.bori_count || null,
                        kiske_dwara: jw.kiske_dwara || null,
                        source_mm_id: jw.source_mm_id,
                        description: jw.description || null,
                        is_received: jw.is_received ? 1 : 0,
                        active: 1
                    };
                    PrastavJawak.insert(jawakData, false);
                }
                return [pId];
            } else {
                // Insert new bunch of prastavs
                const row = db.prepare('SELECT MAX(CAST(voucher_no AS INTEGER)) AS v_no FROM prastav').get();
                voucher_no = (row.v_no || 0) + 1;

                for (const line of lines) {
                    const prastavData = {
                        ...data,
                        voucher_no: voucher_no,
                        item_id: line.item_id,
                        subitem_id: line.subitem_id || null,
                        unit_id: line.unit_id,
                        qty_needs: line.qty_needs || null,
                        qty: line.qty,
                        bachat: line.bachat || 0,
                        monthly_uses: line.monthly_uses || 0,
                        rate: line.rate || 0,
                        amount: line.amount || 0,
                        description: line.description || null,
                    };
                    delete prastavData._id;
                    delete prastavData.lines;

                    const pId = Prastav.insert(prastavData, false);
                    pIds.push(pId);

                    const jawaks = Array.isArray(line.jawaks) ? line.jawaks.filter(j => j.source_mm_id && j.qty) : [];
                    for (const jw of jawaks) {
                        const jawakData = {
                            prastav_id: pId,
                            date: jw.date || data.date,
                            mm_id: data.mm_id,
                            item_id: jw.item_id || line.item_id,
                            subitem_id: jw.subitem_id || line.subitem_id || null,
                            unit_id: line.unit_id,
                            qty: jw.qty,
                            rate: jw.rate || 0,
                            amount: jw.amount || 0,
                            bori_count: jw.bori_count || null,
                            kiske_dwara: jw.kiske_dwara || null,
                            source_mm_id: jw.source_mm_id,
                            description: jw.description || null,
                            is_received: jw.is_received ? 1 : 0,
                            active: 1
                        };
                        PrastavJawak.insert(jawakData, false);
                    }
                }
            }

            sutramDB.commit();
            resultIds = pIds;

        } catch (err) {
            sutramDB.rollback();
            throw err;
        }
    
        res.status(200).json({ success: true, result: resultIds });
    } catch (e) {
        next(e);
    }
});

// Delete prastav (and its jawaks)
router.delete('/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        db.prepare(`DELETE FROM prastav_jawak WHERE prastav_id = ?`).run(id);
        const changes = db.prepare(`DELETE FROM prastav WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

// ── Prastav Jawak lines ───────────────────────────────────────

// Get single prastav_jawak line by id (with joins)
router.get('/jawak/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = PrastavJawak.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update single prastav_jawak line
router.post('/jawak', (req, res, next) => {
    try {
        const data = req.body || {};
        const lineId = data._id
            ? PrastavJawak.updateById(data, Number(data._id), false)
            : PrastavJawak.insert(data, false);

        res.status(200).json({ success: true, result: lineId });
    } catch (e) {
        next(e);
    }
});

// Delete single prastav_jawak line
router.delete('/jawak/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        const changes = db.prepare(`DELETE FROM prastav_jawak WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

module.exports = router;

