const express = require('express');
const router = express.Router();


const { dbmodal } = require('../database/db.model');
const db = dbmodal.db;
const BaseTable = require('../database/base.table');

// ── Simple table instances ──
const Prastav = new BaseTable('prastav');
const PrastavJawak = new BaseTable('prastav_jawak');

// ── Prastav main ──────────────────────────────────────────────

// Get all prastav (with joins)
// Optional query params: active, mm_id, item_id, date
router.get('/', (req, res, next) => {
    try {
        const { active, mm_id, item_id, date } = req.query || {};
        const where = {};

        if (active !== undefined) where.active = (active === '1' || active === 1 || active === true || active === 'true') ? 1 : 0;
        if (mm_id !== undefined && mm_id !== '') where.mm_id = Number(mm_id);
        if (item_id !== undefined && item_id !== '') where.item_id = Number(item_id);
        if (date !== undefined && date !== '') where.date = String(date);

        const rows = Prastav.getAll(where);
        res.status(200).json({ success: true, result: rows });
    } catch (e) {
        next(e);
    }
});

// Get single prastav by id (with joins + jawaks)
router.get('/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = Prastav.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update prastav
router.post('/', (req, res, next) => {
    try {
        const data = req.body || {};
        delete data.voucher_no;   // auto-generated by DB, never from frontend

        // Fulfill Prastav table NOT NULL constraints using the first line
        if (data.lines && data.lines.length > 0) {
            const firstLine = data.lines[0];
            data.item_id = firstLine.item_id;
            data.subitem_id = firstLine.subitem_id || null;
            data.unit_id = firstLine.unit_id;
            data.qty = firstLine.qty;
            data.rate = firstLine.rate || 0;
            data.amount = firstLine.amount || 0;
            data.description = firstLine.description || null;
        }

        let prastavId;
        if (data._id) {
            prastavId = Prastav.updateById(data, Number(data._id), false);
        } else {
            const row = db.prepare('SELECT MAX(CAST(voucher_no AS INTEGER)) AS v_no FROM prastav').get();
            data.voucher_no = (row.v_no || 0) + 1;
            prastavId = Prastav.insert(data, false);
        }

        res.status(200).json({ success: true, result: prastavId });
    } catch (e) {
        next(e);
    }
});

// Delete prastav (and its jawaks)
router.delete('/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        db.prepare(`DELETE FROM prastav_jawak WHERE prastav_id = ?`).run(id);
        const changes = db.prepare(`DELETE FROM prastav WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

// ── Prastav Jawak lines ───────────────────────────────────────

// Get single prastav_jawak line by id (with joins)
router.get('/jawak/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = PrastavJawak.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update single prastav_jawak line
router.post('/jawak', (req, res, next) => {
    try {
        const data = req.body || {};
        const lineId = data._id
            ? PrastavJawak.updateById(data, Number(data._id), false)
            : PrastavJawak.insert(data, false);

        res.status(200).json({ success: true, result: lineId });
    } catch (e) {
        next(e);
    }
});

// Delete single prastav_jawak line
router.delete('/jawak/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        const changes = db.prepare(`DELETE FROM prastav_jawak WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

module.exports = router;

