const express = require('express');
const router = express.Router();


const { dbmodal, sutramDB } = require('../database/db.model');
const db = dbmodal.db;
const BaseTable = require('../database/base.table');
const service = require('../services/prastav.service');

// ── Simple table instances ──
const Prastav = new BaseTable('prastav');
const PrastavJawak = new BaseTable('prastav_jawak');

// ── Prastav main ──────────────────────────────────────────────

// Paginated + Filtered List (PUT used for body-based filters)
router.put('/', (req, res, next) => {
    try {
        const { result, pageNo, total_count } = service.getPrastavs(req.body || {});
        res.status(200).json({ success: true, result, pageNo, total_count });
    } catch (e) {
        next(e);
    }
});

// filter prastav with dept_id
router.put('/filter/:dept_id', (req, res, next) => {
    try {
        const { result, pageNo, total_count } = service.getPrastavs({ ...req.body, dept_id: req.params.dept_id });
        res.status(200).json({ success: true, result, pageNo, total_count });
    } catch (e) {
        next(e);
    }
});

// Get all prastav (legacy GET, optional query params)
router.get('/', (req, res, next) => {
    try {
        const { active, mm_id, item_id, date, year } = req.query || {};
        const { result, total_count } = service.getPrastavs({
            mm_id, item_id, year,
            active: (active === '1' || active === 'true' || active === true) ? 1 : null,
            itemsPerPage: 10000 // Return large set for legacy GET
        });

        res.status(200).json({ success: true, result, total_count });
    } catch (e) {
        next(e);
    }
});

// Get single prastav by id (with joins + jawaks)
router.get('/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = Prastav.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update prastav
router.post('/', (req, res, next) => {
    try {
        const data = req.body || {};
        delete data.voucher_no;   // auto-generated by DB, never from frontend

        const lines = Array.isArray(data.lines) ? data.lines.filter(l => l.item_id || l.item_subitem_id) : [];

        let resultIds;
        sutramDB.begin();
        try {
            let voucher_no;
            let pIds = [];

            // Case B: Generate NEW Voucher No
            const row = db.prepare('SELECT MAX(CAST(voucher_no AS INTEGER)) AS v_no FROM prastav').get();
            voucher_no = (row.v_no || 0) + 1;

            // Insertion Logic
            for (const line of lines) {
                const prastavData = {
                    ...data,
                    voucher_no: voucher_no,
                    item_id: line.item_id,
                    subitem_id: line.subitem_id || null,
                    unit_id: line.unit_id,
                    qty_needs: line.qty_needs || null,
                    qty: line.qty,
                    bachat: line.bachat || 0,
                    monthly_uses: line.monthly_uses || 0,
                    rate: line.rate || 0,
                    amount: line.amount || 0,
                    description: line.description || null,
                    active: 1
                };
                delete prastavData._id;
                delete prastavData.lines;

                const pId = Prastav.insert(prastavData, false);
                pIds.push(pId);

                const jawaks = Array.isArray(line.jawaks) ? line.jawaks.filter(j => j.source_mm_id && j.qty) : [];
                for (const jw of jawaks) {
                    const jawakData = {
                        prastav_id: pId,
                        date: jw.date || data.date,
                        mm_id: data.mm_id,
                        item_id: jw.item_id || line.item_id,
                        subitem_id: jw.subitem_id || line.subitem_id || null,
                        unit_id: jw.unit_id || line.unit_id,
                        qty: jw.qty,
                        rate: jw.rate || 0,
                        amount: jw.amount || 0,
                        bori_count: jw.bori_count || null,
                        kiske_dwara: jw.kiske_dwara || null,
                        source_mm_id: jw.source_mm_id,
                        description: jw.description || null,
                        is_received: jw.is_received ? 1 : 0,
                        active: 1
                    };
                    PrastavJawak.insert(jawakData, false);
                }
            }

            sutramDB.commit();
            resultIds = pIds;

        } catch (err) {
            sutramDB.rollback();
            throw err;
        }

        res.status(200).json({ success: true, result: resultIds });
    } catch (e) {
        next(e);
    }
});

// Delete prastav (and its jawaks)
router.delete('/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        db.prepare(`DELETE FROM prastav_jawak WHERE prastav_id = ?`).run(id);
        const changes = db.prepare(`DELETE FROM prastav WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

// ── Prastav Jawak lines ───────────────────────────────────────

// Get single prastav_jawak line by id (with joins)
router.get('/jawak/:id', (req, res, next) => {
    try {
        const id = Number(req.params.id);
        const row = PrastavJawak.getById(id);
        res.status(200).json({ success: true, result: row });
    } catch (e) {
        next(e);
    }
});

// Create / update single prastav_jawak line
router.post('/jawak', (req, res, next) => {
    try {
        const data = req.body || {};
        const lineId = data._id
            ? PrastavJawak.updateById(data, Number(data._id), false)
            : PrastavJawak.insert(data, false);

        res.status(200).json({ success: true, result: lineId });
    } catch (e) {
        next(e);
    }
});

// Delete single prastav_jawak line
router.delete('/jawak/:id', (req, res, next) => {
    try {
        const id = req.params.id;
        const changes = db.prepare(`DELETE FROM prastav_jawak WHERE _id = ?`).run(id).changes;
        res.status(200).json({ success: true, result: changes });
    } catch (e) {
        next(e);
    }
});

// ── Voucher endpoints ─────────────────────────────────────────

// Get full voucher data by voucher_no
router.get('/voucher/:vno', (req, res, next) => {
    try {
        const result = service.getVoucher(req.params.vno);
        res.status(200).json({ success: true, result });
    } catch (e) {
        next(e);
    }
});

// Delete entire voucher by voucher_no
router.delete('/voucher/:vno', (req, res, next) => {
    try {
        const result = service.deleteVoucher(req.params.vno);
        res.status(200).json({ success: true, result });
    } catch (e) {
        next(e);
    }
});

// Update entire voucher by voucher_no
router.put('/voucher/:vno', (req, res, next) => {
    try {
        const result = service.updateVoucher(req.params.vno, req.body || {});
        res.status(200).json({ success: true, result });
    } catch (e) {
        next(e);
    }
});

module.exports = router;

