import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ExcelImportService {

  importList: any = [
    { name: 'destribution' },
    { name: 'bachat', note: 'final bachat list that make through actual counting. Here ignore Marking on qty 0.' },
    { name: 'pbk', autoUpdate: true },
    { name: 'vehicle', secondHeader: false, autoUpdate: true },
    { name: 'nimitt', autoUpdate: true },
    { name: 'item', autoUpdate: true },
    { name: 'rel_item_category', autoUpdate: true },
    { name: 'subitem', autoUpdate: true },
    { name: 'rel_subitem_category', autoUpdate: true },
    { name: 'subitem_list', autoUpdate: true },
    { name: 'product', autoUpdate: true },
    { name: 'support_list', autoUpdate: true, note: 'list_type should be aawak_type, jawak_type, gender, relation, condition. MUST BE same spelling, lower case.' },
    { name: 'category', autoUpdate: true },
    { name: 'district', autoUpdate: true },
    { name: 'attribute', autoUpdate: true },
    { name: 'attributes_value', autoUpdate: true },
    { col_name: 'variant', autoUpdate: true, note: 'Import variants with comma-separated attributes.' },
    { name: 'jawak', autoUpdate: true, note: 'Either PBK (Sewadhari) or Jawak MM (Destination) is mandatory.' },
  ];
  config: any = {
    vehicle: [
      { col_name: 'mm', name: 'mm', alt_names: ["mm_name", "mm name", "मि.म.", "मि म", "मिनी मधुबन"], not_null: true, ref_table: 'mm', ref_field: 'mm_id', ref_data: 'mm_hin' },
      { col_name: 'vehicle_type', name: 'vehicle_type', alt_names: ["vehicle type", "gadi type", "gadi_type"], not_null: false },
      { col_name: 'gadi_name', name: 'gadi_name', alt_names: ["gadi name", "vehicle name", "vehicle_name"], not_null: false },
      { col_name: 'gadi_num', name: 'gadi_num', alt_names: ["gadi num", "vehicle num", "vehicle_num", "gadi_no", "gadi no", "vehicle no", "vehicle_no"], not_null: true },
      { col_name: 'fuel_type', name: 'fuel_type', alt_names: ["fuel type", "fuel"], not_null: false },
      { col_name: 'seating_capacity', name: 'seating_capacity', alt_names: ["seating capacity"], not_null: false },
      { col_name: 'owner_name', name: 'owner_name', alt_names: ["owner", "owner name"], not_null: false },
      { col_name: 'nominee', name: 'nominee', alt_names: ["nomini"], not_null: false },
      { col_name: 'aawak_type', name: 'aawak_type', alt_names: ["aawak type", "awk type", "awk_type"], not_null: true },
      { col_name: 'rc_date', name: 'rc_date', type: 'unix_date', alt_names: ['rc'], not_null: false },
      { col_name: 'rc_exp_date', name: 'rc_exp_date', type: 'unix_date', alt_names: ["rc expiry", "rc_expiry", "rc exp"], not_null: false },
      { col_name: 'rc_amount', name: 'rc_amount', alt_names: ["rc amount", "rc_amt", "rc amt"], not_null: false },
      { col_name: 'insurance_date', name: 'insurance_date', type: 'unix_date', alt_names: ["ins", "insurance"], not_null: false },
      { col_name: 'insurance_exp_date', name: 'insurance_exp_date', type: 'unix_date', alt_names: ["insurance_expiry", "insurance expiry", "insurance_exp", "insurance exp", "ins expiry", "ins_expiry", "ins exp", "ins_exp"], not_null: false },
      { col_name: 'insurance_type', name: 'insurance_type', alt_names: ["insurance type", "insurance_party", "insurance party", "ins party", "ins_party"], not_null: false },
      { col_name: 'insurance_amount', name: 'insurance_amount', alt_names: ["insurance amount", "insurance_amt", "insurance amt", "ins amount", "ins_amount", "ins_amt", "ins amt"], not_null: false },
      { col_name: 'puc_date', name: 'puc_date', type: 'unix_date', alt_names: ['puc'], not_null: false },
      { col_name: 'puc_exp_date', name: 'puc_exp_date', type: 'unix_date', alt_names: ["puc_expiry", "puc expiry", "puc_exp", "puc exp"], not_null: false },
      { col_name: 'puc_amount', name: 'puc_amount', alt_names: ["puc amount", "puc_amt", "puc amt"], not_null: false },

    ],
    product: [
      { col_name: 'sr_num', name: 'sr_no', alt_names: ["sr no", "sr number", "sr num", "sr_num", "serial no"], not_null: false },
      { col_name: 'product_code', name: 'product_code', alt_names: ["product code", "pr_code", "pr code"], not_null: false },
      { col_name: 'purchase_date', name: 'purchase_date', alt_names: ["date", "तारीख"], not_null: false },
      { col_name: 'mm', name: 'mm', alt_names: ["mm_name", "mm name", "मि.म.", "मि म", "मिनी मधुबन"], not_null: true, ref_table: 'mm', ref_field: 'mm_id', ref_data: 'mm_hin' },
      { col_name: 'item', name: 'item', alt_names: ["item_name", "item name", "आइटम", "आइटम का नाम"], not_null: true, ref_table: 'item', ref_field: 'item_id', ref_data: 'item_hin' },
      { col_name: 'subitem', name: 'subitem', alt_names: ["subitem_name", "subitem name", "सबआइटम", "सबआइटम का नाम"], not_null: false, ref_table: 'subitem', ref_field: 'subitem_id', ref_data: 'subitem_hin' },
      { col_name: 'qty', name: 'qty', alt_names: ["quantity", "संख्या"], not_null: true },
      { col_name: 'unit', name: 'unit', alt_names: ["यूनिट"], not_null: true, ref_table: 'unit', ref_field: 'unit_id', ref_data: 'unit_short' },
      { col_name: 'aawak_type', name: 'aawak_type', alt_names: ["आवक टाइप"], not_null: true, ref_table: 'aawak_type', ref_field: 'aawak_type_id', ref_data: 'list_name_hin' },
      { col_name: 'company_name', name: 'company', alt_names: ["company_name", "कंपनी", "company", "company name"], not_null: false },
      { col_name: 'modal_name', name: 'modal', alt_names: ["modal_name", "modal name", "मोडेल"], not_null: false },
      { col_name: 'condition', name: 'condition', alt_names: ["कन्डिशन"], not_null: true, ref_table: 'condition', ref_field: 'condition_id', ref_data: 'list_name_hin' },
      { col_name: 'warranty_period', name: 'warranty_period', alt_names: ["वॉरन्टी समय", "वॉरन्टी", "warranty", "warranty period"], not_null: false },
      { col_name: 'warranty_from', name: 'warranty_from', alt_names: ["warranty from", "वॉरन्टी कहाँ से ?", "वॉरन्टी कहाँ से"], not_null: false },
      { col_name: 'purchase_from', name: 'purchase_from', alt_names: ["purchase from", "कहाँ से खरीदा"], not_null: false },
      { col_name: 'purchased_by', name: 'purchased_by', alt_names: ["purchased by", "purchase by", "किसके थ्रू"], not_null: false },
      { col_name: 'product_detail', name: 'product_detail', alt_names: ["product detail", "डेटाइल माहिती"], not_null: false },
      { col_name: 'accessories', name: 'accessories', alt_names: ["साथ मे क्या2 आया"], not_null: false },
      { col_name: 'nimmit', name: 'nimmit', alt_names: ["निमित्त"], not_null: false, ref_table: 'nimitt', ref_field: 'nimitt_id', ref_data: 'nimitt_hin' },

    ],
    pbk: [
      { col_name: 'roll_no', name: 'roll_no', alt_names: ["roll no", "ro no", "रोल नंबर", "रोल नं", "roll number", "rollno"], not_null: false, },
      { col_name: 'pbk_hin', name: 'pbk_hin', alt_names: ["pbk hin", "namehin"], not_null: true, },
      { col_name: 'pbk_eng', name: 'pbk_eng', alt_names: ["pbk eng", "nameeng"], not_null: false, },
      { col_name: '_gender', name: '_gender', alt_names: ["gender"], not_null: true, ref_table: 'gender', ref_field: 'gender', ref_data: 'list_name_eng' },
      { col_name: 'state', name: 'state', alt_names: ["स्टेट", "राज्य"], not_null: true, ref_table: 'state', ref_field: 'state_id', ref_data: 'state_hin' },
      { col_name: '_relation', name: '_relation', alt_names: ["relation"], not_null: false, ref_table: 'relation', ref_field: 'relation', ref_data: 'list_name_eng' },
      { col_name: 'relative_name', name: 'relative_name', alt_names: ["relative name", "relativename"], not_null: false, },
      { col_name: 'birth_date', name: 'birth_date', alt_names: ["date of birth", "dob", "birth date", "जन्म तारीख"], type: 'date', not_null: false },
      { col_name: 'age', name: 'age', alt_names: ["उम्र"], not_null: false },
      { col_name: 'address', name: 'address', alt_names: ["पता"], not_null: false },
      { col_name: 'townarea', name: 'townarea', alt_names: ["town area", "town_area", "गाव", "village"], not_null: false },
      { col_name: 'district', name: 'district', alt_names: ["district_hin", "district_eng", "जिला", "district hin", "district eng"], not_null: false, ref_table: 'district', ref_field: 'district_id', ref_data: 'district_hin' },
      { col_name: 'city', name: 'city', alt_names: ["city_hin", "city_eng", "शहर"], not_null: false, ref_table: 'city', ref_field: 'city_id', ref_data: 'city_hin' },
      { col_name: 'mo_no', name: 'mo_no', alt_names: ["mobile no", "mobile number", "mo no", "mobileno"], not_null: false },
      { col_name: 'alt_mo_no', name: 'alt_mo_no', alt_names: ["alternative mobile no", "alternative mobile number", "alt mo no", "alt mobile no"], not_null: false },
      { col_name: 'class_mm', name: 'class_mm', alt_names: ["mm_name", "mm name", "मि.म.", "क्लास मि म", "क्लास मिनी मधुबन", "daily class mm", "class mm name", "क्लास मि.म.", "मि म", "मिनी मधुबन"], not_null: false, ref_table: 'mm', ref_field: 'class_mm_id', ref_data: 'mm_hin' },
      { col_name: 'bhatti_date', name: 'bhatti_date', alt_names: ["bhatti date", "भट्ठी तारीख", "भट्ठी कब किया", "भट्ठी कब किया?", "bhattiyear", "bhatti year"], type: 'date', not_null: false },

    ],
    nimitt: [
      { col_name: 'roll_no', name: 'roll_no', alt_names: ["roll no", "ro no", "रोल नंबर", "रोल नं", "roll number", "rollno"], not_null: false, },
      { col_name: 'nimitt_hin', name: 'nimitt_hin', alt_names: ["nimitt hin", "namehin"], not_null: true, },
      { col_name: 'nimitt_eng', name: 'nimitt_eng', alt_names: ["nimitt eng", "nameeng"], not_null: false, },
      { col_name: 'gender', name: 'gender', alt_names: [], not_null: true, ref_table: 'gender', ref_field: 'gender', ref_data: 'list_name_eng  ' },
      { col_name: 'state', name: 'state', alt_names: ["स्टेट", "राज्य"], not_null: true, ref_table: 'state', ref_field: 'state_id', ref_data: 'state_hin' },
      { col_name: 'relative_name', name: 'father_name', alt_names: ["father name", "relative name", "fathername"], not_null: false, },
      { col_name: 'townarea', name: 'townarea', alt_names: ["town area", "town_area", "गाव", "village"], not_null: false },
    ],
    subitem: [
      { col_name: 'item_hin', name: 'item_hin', alt_names: ["itemhin", "item hin", "item"], not_null: true, ref_table: "item", ref_field: "item_id", ref_data: "item_hin" },
      { col_name: 'item_eng', name: 'item_eng', alt_names: ["itemeng", "item eng"], not_null: false, },
      { col_name: 'item_roman', name: 'item_roman', alt_names: ["itemroman", "item roman"], not_null: false, },
      { col_name: 'item_code', name: 'item_code', alt_names: ["itemcode", "item code"], not_null: false, },
      { col_name: 'subitem_hin', name: 'subitem_hin', alt_names: ["subitemhin", "subitem hin", "subitem"], not_null: true },
      { col_name: 'subitem_eng', name: 'subitem_eng', alt_names: ["subitemeng", "subitem eng"], not_null: false, },
      { col_name: 'subitem_roman', name: 'subitem_roman', alt_names: ["subitemroman", "subitem roman"], not_null: false, },
      { col_name: 'unit', name: 'unit', alt_names: [], not_null: false, },
      { col_name: 'extra_note', name: 'extra_note', alt_names: ["extra note", "extranote"], not_null: false, },
      { col_name: 'restrict_month', name: 'restrict_month', alt_names: ["restrict month"], not_null: false },
      { col_name: 'restrict_year', name: 'restrict_year', alt_names: ["restrict year"], not_null: false },
      { col_name: 'min_rate', name: 'min_rate', alt_names: ["min rate"], not_null: false },
      { col_name: 'max_rate', name: 'max_rate', alt_names: ["max rate"], not_null: false },
    ],
    item: [
      { col_name: 'item_hin', name: 'item_hin', alt_names: ["itemhin", "item hin"], not_null: true, },
      { col_name: 'item_eng', name: 'item_eng', alt_names: ["itemeng", "item eng"], not_null: false, },
      { col_name: 'item_roman', name: 'item_roman', alt_names: ["itemroman", "item roman"], not_null: false, },
      { col_name: 'item_code', name: 'item_code', alt_names: ["itemcode", "item code"], not_null: false, },
      { col_name: 'aliases', name: 'aliases', alt_names: ["alternative names", "alias", "aliases"], not_null: false, type: "array" },
      { col_name: 'unit', name: 'unit', alt_names: ['default_unit', 'default unit'], not_null: false, ref_table: "unit", ref_field: "unit_id", ref_data: "unit.unit_short" },
      { col_name: 'extra_note', name: 'extra_note', alt_names: ["extra note", "extranote"], not_null: false, },
      { col_name: 'restrict_month', name: 'restrict_month', alt_names: ["restrict month"], not_null: false },
      { col_name: 'restrict_year', name: 'restrict_year', alt_names: ["restrict year"], not_null: false },
      { col_name: 'min_rate', name: 'min_rate', alt_names: ["min rate"], not_null: false },
      { col_name: 'max_rate', name: 'max_rate', alt_names: ["max rate"], not_null: false },
    ],
    rel_item_category: [
      { col_name: 'item_hin', name: 'item_hin', alt_names: ["itemhin", "item hin"], not_null: true, ref_table: 'item', ref_field: 'item_id', ref_data: 'item_hin' },
      { col_name: 'category', name: 'categories', alt_names: ["category", "categories"], not_null: true, ref_table: 'category', ref_field: 'category_id', ref_data: 'category_hin' }
    ],
    rel_subitem_category: [
      { col_name: 'item_hin', name: 'item_hin', alt_names: ["itemhin", "item hin"], not_null: true, ref_table: 'item', ref_field: 'item_id', ref_data: 'item_hin' },
      { col_name: 'subitem_hin', name: 'subitem_hin', alt_names: ["subitemhin", "subitem hin", "subitem"], not_null: true, ref_table: 'subitem', ref_field: 'subitem_id', ref_data: 'subitem_hin' },
      { col_name: 'category', name: 'categories', alt_names: ["category", "categories"], not_null: true, ref_table: 'category', ref_field: 'category_id', ref_data: 'category_hin' }
    ],
    support_list: [
      { col_name: 'list_type', name: 'list_type', alt_names: ["list type"], not_null: true },
      { col_name: 'list_name_hin', name: 'list_name_hin', alt_names: ["list name hin"], not_null: false },
      { col_name: 'list_name_eng', name: 'list_name_eng', alt_names: ["list name eng"], not_null: true },
      { col_name: 'list_name_roman', name: 'list_name_roman', alt_names: ["list name roman"], not_null: false },
      { col_name: 'active', name: 'active', alt_names: [], not_null: false },
    ],
    category: [
      { col_name: 'parent_category', name: 'parent_category', alt_names: ['parent category', 'parent'], not_null: false, ref_table: "category", ref_field: "parent_id", ref_data: "parent_category_hin" },
      { col_name: 'category_eng', name: 'category_eng', alt_names: ['category eng', 'category (hin)'], not_null: false },
      { col_name: 'category_hin', name: 'category_hin', alt_names: ['category hin', 'category (eng)'], not_null: true },
      { col_name: 'category_roman', name: 'category_roman', alt_names: ['category roman', 'category (roman)'], not_null: false },
    ],
    district: [
      { col_name: 'district_hin', name: 'district_hin', alt_names: ["district hin", "namehin"], not_null: true, },
      { col_name: 'district_eng', name: 'district_eng', alt_names: ["district eng", "nameeng"], not_null: true, },
      { col_name: 'state', name: 'state', alt_names: ["स्टेट", "राज्य"], not_null: true, ref_table: 'state', ref_field: 'state_id', ref_data: 'state_hin' },
    ],
    bachat: [
      { col_name: 'sn', name: 'sn', alt_names: ["sr no", "sr number", "sr num", "sr_num", "serial no"], not_null: false },
      { col_name: 'date', name: 'date', type: 'date', alt_names: ["तारीख"], not_null: true },
      { col_name: 'mm', name: 'mm', alt_names: ["mm_name", "mm name", "मि.म.", "मि म", "मिनी मधुबन"], not_null: true, ref_table: 'mm', ref_field: 'mm_id', ref_data: 'mm_hin' },
      { col_name: 'item', name: 'item', alt_names: ["item_name", "item name", "आइटम", "आइटम का नाम"], not_null: true, type: 'mix', ref_table: 'item', ref_field: 'item_id', ref_data: 'item_hin' },
      { col_name: 'subitem', name: 'subitem', alt_names: ["subitem_name", "subitem name", "सबआइटम", "सबआइटम का नाम"], not_null: false, ref_table: 'subitem', ref_field: 'subitem_id', ref_data: 'subitem_hin' },
      { col_name: 'company_name', name: 'company', alt_names: ["company_name", "कंपनी", "company", "company name"], not_null: false },
      { col_name: 'qty', name: 'qty', alt_names: ["quantity", "संख्या", "number"], not_null: true },
      { col_name: 'unit', name: 'unit', alt_names: ["यूनिट"], not_null: true, ref_table: 'unit', ref_field: 'unit_id', ref_data: 'unit_short' },
      { col_name: 'condition', name: 'condition', alt_names: ["कन्डिशन"], not_null: false, ref_table: 'condition', ref_field: 'condition_id', ref_data: 'list_name_hin' },
      { col_name: 'actual_amt', name: 'amount', alt_names: ["अमाउन्ट", "amt", "amount"], not_null: false },
      { col_name: 'item_detail', name: 'item_detail', alt_names: ["item detail", "डेटाइल माहिती"], not_null: false },
      { col_name: 'description', name: 'description', alt_names: ["note", "डिस्क्रिप्शन", "नोट"], not_null: false },
      { col_name: 'nimmit', name: 'nimmit', alt_names: ["निमित्त"], not_null: false, ref_table: 'nimitt', ref_field: 'nimitt_id', ref_data: 'nimitt_hin' },
    ],
    attribute: [
      { col_name: 'attribute_hin', name: 'attribute_hin', alt_names: ['attribute hin', 'attr hin'], not_null: true },
      { col_name: 'attribute_eng', name: 'attribute_eng', alt_names: ['attribute eng', 'attr eng'], not_null: false },
      { col_name: 'attribute_roman', name: 'attribute_roman', alt_names: ['attribute roman', 'attr roman'], not_null: false },
    ],
    attributes_value: [
      { col_name: 'attribute', name: 'attribute', alt_names: ['attribute_hin', 'attribute hin', 'attr'], not_null: true, ref_table: 'attribute', ref_field: 'attribute_id', ref_data: 'attribute_hin' },
      { col_name: 'attribute_value_hin', name: 'attribute_value_hin', alt_names: ['value hin', 'value_hin'], not_null: true },
      { col_name: 'attribute_value_eng', name: 'attribute_value_eng', alt_names: ['value eng', 'value_eng'], not_null: false },
      { col_name: 'attribute_value_roman', name: 'attribute_value_roman', alt_names: ['value roman', 'value_roman'], not_null: false },
    ],
    variant: [
      { col_name: 'item', name: 'item', alt_names: ["item_hin", "item hin", "item name"], not_null: true, ref_table: "item", ref_field: "item_id", ref_data: "item_hin" },
      { col_name: 'display_name_hin', name: 'display_name_hin', alt_names: ['variant_hin', 'variant hin', 'display name hin'], not_null: true },
      { col_name: 'display_name_eng', name: 'display_name_eng', alt_names: ['variant_eng', 'variant eng', 'display name eng'], not_null: false },
      { col_name: 'display_name_roman', name: 'display_name_roman', alt_names: ['variant_roman', 'variant roman', 'display name roman'], not_null: false },
      { col_name: 'attributes_hin', name: 'attribute_values', alt_names: ['attributes hin', 'attrs hin'], not_null: true, type: 'array', ref_table: 'attributes_value', ref_field: 'attribute_values', ref_data: 'attribute_value_hin' },
      { col_name: 'attributes_eng', name: 'attributes_eng', alt_names: ['attributes eng', 'attrs eng'], not_null: false },
      { col_name: 'attributes_roman', name: 'attributes_roman', alt_names: ['attributes roman', 'attrs roman'], not_null: false },
      { col_name: 'sku', name: 'sku', alt_names: ['variant_sku', 'variant sku'], not_null: false },
      { col_name: 'unit', name: 'unit', alt_names: ['यूनिट'], not_null: false, ref_table: 'unit', ref_field: 'unit_id', ref_data: 'unit_short' },
      { col_name: 'min_rate', name: 'min_rate', alt_names: ["min rate"], not_null: false },
      { col_name: 'max_rate', name: 'max_rate', alt_names: ["max rate"], not_null: false },
    ],
    jawak: [
      { col_name: 'date', name: 'date', type: 'date', alt_names: ["तारीख", "jawak date", "date"], not_null: true },
      { col_name: 'mm', name: 'mm', alt_names: ["mm_name", "mm name", "मि.म.", "मि म", "मिनी मधुबन"], not_null: true, ref_table: 'mm', ref_field: 'mm_id', ref_data: 'mm_hin' },
      { col_name: 'jawak_mm', name: 'jawak_mm', alt_names: ["jawak mm", "sent to mm", "destination mm", "kaha bheja", "कहाँ भेजा"], not_null: false, ref_table: 'mm', ref_field: 'jawak_mm_id', ref_data: 'mm_hin' },
      { col_name: 'pbk', name: 'pbk', alt_names: ["pbk name", "sewadhari", "name", "नाम"], not_null: false, ref_table: 'pbk', ref_field: 'pbk_id', ref_data: 'pbk_hin' },
      { col_name: 'item', name: 'item', alt_names: ["item_name", "item name", "आइटम", "आइटम का नाम"], not_null: true, ref_table: 'item', ref_field: 'item_id', ref_data: 'item_hin' },
      { col_name: 'subitem', name: 'subitem', alt_names: ["subitem_name", "subitem name", "सबआइटम", "सबआइटम का नाम"], not_null: false, ref_table: 'subitem', ref_field: 'subitem_id', ref_data: 'subitem_hin' },
      { col_name: 'qty', name: 'qty', alt_names: ["quantity", "संख्या", "qty"], not_null: true },
      { col_name: 'unit', name: 'unit', alt_names: ["यूनिट"], not_null: true, ref_table: 'unit', ref_field: 'unit_id', ref_data: 'unit_short' },
      { col_name: 'jawak_type', name: 'jawak_type', alt_names: ["जावक टाइप", "jawak type", "jawak_type"], not_null: true, ref_table: 'jawak_type', ref_field: 'jawak_type_id', ref_data: 'list_name_hin' },
      { col_name: 'condition', name: 'condition', alt_names: ["कन्डिशन", "condition"], not_null: false, ref_table: 'condition', ref_field: 'condition_id', ref_data: 'list_name_hin' },
      { col_name: 'nimitt', name: 'nimitt', alt_names: ["निमित्त", "nimitt"], not_null: false, ref_table: 'nimitt', ref_field: 'nimitt_id', ref_data: 'nimitt_hin' },
      { col_name: 'pkt_num', name: 'pkt_num', alt_names: ["packet no", "pkt no", "pkt_no", "पैकेट नं"], not_null: false },
      { col_name: 'voucher_no', name: 'voucher_no', alt_names: ["voucher no", "vch no", "वाउचर नं"], not_null: false },
      { col_name: 'rate', name: 'rate', alt_names: ["रेट", "rate"], not_null: false },
      { col_name: 'actual_amt', name: 'amount', alt_names: ["अमाउन्ट", "amt", "amount", "कुल राशि"], not_null: false },
      { col_name: 'description', name: 'description', alt_names: ["note", "डिस्क्रिप्शन", "नोट", "विवरण"], not_null: false },
      { col_name: 'usage_list', name: 'usage_list', alt_names: ["usage category", "उपयोग श्रेणी"], not_null: false, ref_table: 'usage_list', ref_field: 'usage_list_id', ref_data: 'list_name_hin' },
      { col_name: 'sell_repair_place', name: 'place', alt_names: ["sent to place", "sell repair place", "जगह"], not_null: false },
      { col_name: 'lot_no', name: 'lot_no', alt_names: ["lot no", "lot", "लॉट नं"], not_null: false },
      { col_name: 'reg_pg_no', name: 'reg_pg_no', alt_names: ["reg pg no", "page no", "रजिस्टर पेज नं"], not_null: false },
      { col_name: 'container_qty', name: 'container_qty', alt_names: ["container qty", "कंटेनर संख्या"], not_null: false },
    ],
  }
  constructor() { }

  generateSequencialArray(count: number) {
    return Array(count).keys();
  }
}
